# Use an image that includes Maven for the build stage
FROM maven:3.8-openjdk-17 AS build

# Set the working directory
WORKDIR /app

# Copy the pom.xml file and the source code
COPY pom.xml .
COPY src ./src


# Build the Spring Boot application using Maven
RUN mvn clean install -DskipTests

# Stage 2: Run the Spring Boot app in a smaller container
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the jar file from the build stage
COPY --from=build /app/target/*.war /app/app.jar

# Expose the port Spring Boot is running on
EXPOSE 8080

# Command to run the Spring Boot app
CMD ["java", "-jar", "app.jar"]