spring:
  application:
    name: timetable-service
  profiles:
    active: default
#  config:
#    import: "configserver:http://localhost:8071"
#  cloud:
#    config:
#      uri: http://localhost:8071


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
